// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgwjxjwpfglbfrqmszwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnd2p4andwZmdsYmZycW1zendpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTk1NzYsImV4cCI6MjA2NDMzNTU3Nn0.WufcKjWpuBHWL2MrQlU270ptIGOKRC3lvPGUKD4fFGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);